{% set name = "napari-bioformats" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9361bf87158599b2aa57143265f5e48cc9a1901a9fc2897b2c74b8f2462a9e03

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - napari-plugin-engine >=0.1.4
    - numpy
    - pims
    - jpype1
    - ome-types

test:
  imports:
    - napari_bioformats
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/tlambert03/napari-bioformats
  summary: Bioformats for napari, using pims
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/tlambert03/napari-bioformats

extra:
  recipe-maintainers:
    - tlambert03
